name: Pull Request

# Run on PRs.
on: [pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pylint pytest requests
    - name: Compile
      run: |
        python -m py_compile siaskynet/*.py
    - name: Lint
      if: matrix.python-version >= 3.0
      run: |
        flake8 siaskynet/ --count --show-source --statistics --per-file-ignores="__init__.py:F401"
        # Disable lint that complains about short names.
        pylint siaskynet/ -d invalid-name,protected-access
    - name: Test
      run: |
        pytest
